name: Will Farrow
favicon: null
layout_spectrum: 0.27637130464427173
typography_spectrum: 0.17477854900062084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7254758586641401
  lightness: 0.4499682020395994
  saturation: 0.4388600562233478
  rhythmicContrast: 0.37829293333925307
purpose: []
